[vle.login]
username = "myusername"
password = "mypassword"

[paths]
data = "data"
announcements = "announcements_{date}_{module}.html"

[[modules]]
name = "module1"
targets = [
    {
        name = "Announcements",
        files = false,
        file_matcher = "",
    }
]

[[modules]]
name = "module2"
targets = [
    {
        name = "Lectures",
        files = true,
        file_matcher = ".*\.pdf",
    }
]
